#!/bin/sh
. /etc/rc.common
 
StartService() {
	open /Users/aaronsmith/dev/_projects/_git/ejectlet/build/Release/ejectlet.app
}

StopService() {
	killall -9 ejectlet
}
 
RestartService() {
	StopService
	StartService
}
 
RunService "$1"